services:
  web:
    build: .
    image: registry.dis.cwi.nl/induxr-orchestrator
    restart: always
    environment:
      - PORT=8090
      - LOG_LEVEL=debug
      - MONGODB_CONNECTION=mongodb://user:pass@mongodb/induxr?authSource=admin
    volumes:
      - ./config/:/code/config
      - ./slides/:/code/slides
      - ./plugins/:/code/plugins
      - ./.env:/code/.env
    ports:
      - "8090:8090"
    command: yarn start
    logging:
      options:
        max-size: "200k"
        max-file: "3"
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db

